name: Build and Deploy Sphinx Docs

on:
  push:
    branches: [ master ] 

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx
        pip install -r requirements.txt || true

    - name: Build Sphinx HTML
      working-directory: OptimTrajectoire-package/source 
      run: |
        make html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: OptimTrajectoire-package/source/_build/html
